# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  foo:
    # The type of runner that the job will run on
    runs-on: [self-hosted, vivado]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run
        run: |
          if (-not (Get-Command git -ErrorAction SilentlyContinue)) {
            Write-Host "Git not found. Installing Git..."
            winget install --id Git.Git -e --source winget --silent --accept-package-agreements --accept-source-agreements
          } else {
              Write-Host "Git is already installed."
          }

      - name: ssh
        shell: powershell
        run: |
          $cap = Get-WindowsCapability -Online | Where-Object Name -like 'OpenSSH.Server*'
          if ($cap.State -ne 'Installed') {
              Add-WindowsCapability -Online -Name $cap.Name
          }

          Start-Service sshd
          Set-Service -Name sshd -StartupType Automatic

          if (-not (Get-NetFirewallRule -Name 'OpenSSH-Server-In-TCP' -ErrorAction SilentlyContinue)) {
              New-NetFirewallRule -Name 'OpenSSH-Server-In-TCP' `
                  -DisplayName 'OpenSSH Server (sshd)' `
                  -Enabled True -Direction Inbound -Protocol TCP `
                  -Action Allow -LocalPort 22
          }
